HISTFILE=~/.history
HISTSIZE=10000000
SAVEHIST=10000000

export HISTFILE HISTSIZE SAVEHIST

setopt SHARE_HISTORY 
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE #ignore if the command start with a space

